package Visao.controle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuBar;

import javafx.scene.control.Label;

import javafx.scene.layout.Pane;

import javafx.scene.control.Menu;

import javafx.scene.control.TableColumn;

public class BuscaControle implements Initializable {
	@FXML
	private Pane paneMenuBusca;
	@FXML
	private MenuBar mbbusca;
	@FXML
	private Menu btnInserirAnun;
	@FXML
	private Menu btnMeusAnun;
	@FXML
	private Label lbbuscar;
	@FXML
	private TextField txtbuscar;
	@FXML
	private TableColumn tblNome;
	@FXML
	private TableColumn tblAno;
	@FXML
	private TableColumn tblCor;
	@FXML
	private TableColumn tblPreco;
	@FXML
	private Button btnBuscarAnun;
	@FXML
	private Button btnAbrirAnun;

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		
		
	}
	
	// Event Listener on Menu[#btnInserirAnun].onAction
	@FXML
	public void inserirAnuncio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Menu[#btnMeusAnun].onAction
	@FXML
	public void listarMeusAnuncios(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBuscarAnun].onAction
	@FXML
	public void buscarAnuncio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAbrirAnun].onAction
	@FXML
	public void abrirAnuncio(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
