package visao.controle;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;
import modelo.dominio.Anuncio;
import negocio.AnuncioNegocio;
import javafx.scene.control.Menu;
import javafx.scene.control.TableColumn;

public class BuscarControle implements Initializable{
	@FXML
	private Pane paneMenuBusca;
	@FXML
	private MenuBar mbbusca;
	@FXML
	private Menu btnInserirAnun;
	@FXML
	private Menu btnMeusAnun;
	@FXML
	private Label lbbuscar;
	@FXML
	private TextField txtbuscar;
	@FXML
	private Button btnBuscarAnun;
	@FXML
	private TableColumn<Anuncio, String> tblNome;
	@FXML
	private TableColumn<Anuncio, String> tblAno;
	@FXML
	private TableColumn<Anuncio, String> tblCor;
	@FXML
	private TableColumn<Anuncio, String> tblValor;
	@FXML
	private Button btnAbrirAnun;
	@FXML
	private MenuItem menuAnuncio, menuMeusAnuncios;
	
	// Event Listener on MenuItem[#menuInserirAnuncio].onAction
	@FXML
	public void listarAnuncio(ActionEvent event) {
		URL arquivoFXML;
		arquivoFXML = getClass().getResource("/visao/telas/Anuncio.fxml");
		
		Parent fxmlParent = null;
		try {
			fxmlParent = (Parent) FXMLLoader.load(arquivoFXML);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		paneMenuBusca.getChildren().clear();
		paneMenuBusca.getChildren().add(fxmlParent);
	}
	
	// Event Listener on MenuItem[#menuMeusAnuncios].onAction
	@FXML
	public void meusAnuncios(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBuscarAnun].onAction
	@FXML
	public void buscarAnuncio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAbrirAnun].onAction
	@FXML
	public void abrirAnuncio(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {

	}
	
	public List<Anuncio> listarAnuncio() throws SQLException {
		List<Anuncio> listaDeAnuncio = new ArrayList<Anuncio>();
		
		AnuncioNegocio negocio = new AnuncioNegocio();
		listaDeAnuncio = negocio.listarAnuncio();
		
		return listaDeAnuncio;
	}
	
}
