package Visao.controle;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import Modelo.dominio.Usuario;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.Hyperlink;

import javafx.scene.layout.Pane;
import negocio.LoginNegocio;

public class LoginControle {
	@FXML
	private Pane paneLogin;
	@FXML
	private Label lbLogin;
	@FXML
	private TextField txtLogin;
	@FXML
	private Label lbSenha;
	@FXML
	private PasswordField pswSenha;
	@FXML
	private Button btnLogin;
	@FXML
	private Hyperlink hplCadastro;
	@FXML
	private Hyperlink hplEsqueciSenha;
	
	LoginNegocio loginNeg = new LoginNegocio();

	// Event Listener on TextField[#txtLogin].onMouseClicked
	@FXML
	public void limpar(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void logar(ActionEvent event) {
		Usuario user = new Usuario();
		String salvo = "salvo";
		user.setLogin(txtLogin.getText());
		user.setSenha(pswSenha.getText());
		salvo = loginNeg.fazerLogin(user);
		if(salvo.equals("salvo")){
			
		}
		limparCampos();
		
	}
	private void limparCampos() {
		// TODO Auto-generated method stub
		
	}
	// Event Listener on Hyperlink[#hplCadastro].onAction
	@FXML
	public void criarCadastro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Hyperlink[#hplEsqueciSenha].onAction
	@FXML
	public void esqueciSenha(ActionEvent event) {
		// TODO Autogenerated
	}
}
