package Visao.controle;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.Pane;

public class PessoaControle {
	@FXML
	private Pane paneCadPessoas;
	@FXML
	private Label lbcadpessoas;
	@FXML
	private Label lbNome;
	@FXML
	private TextField txtNome;
	@FXML
	private Label lbCPF;
	@FXML
	private TextField txtCPF;
	@FXML
	private Label lbEndereco;
	@FXML
	private TextField txtEndereco;
	@FXML
	private Label lbTelefone;
	@FXML
	private TextField txtTelefone;
	@FXML
	private Label lbEmail;
	@FXML
	private TextField txtEmail;
	@FXML
	private Label lbSenha;
	@FXML
	private TextField txtSenha;
	@FXML
	private Button btnSalvar;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnSalvar].onAction
	@FXML
	public void salvar(ActionEvent event) {
		// TODO Autogenerated
	}
}
